### ISSUE TITLE
Blender 2.93 Installation fails

### ISSUE THREAD

**Issue by berriganator** [PyrApple/io_export_catt#2]
Hello: I tried to install your Add-on in the latest version of Blender for Mac (2.93.5) and got the error "Please upgrade to version 2.8." Assuming it does not work with the latest version, I downloaded 2.79b (the latest version supported as indicated here). However, when I go to install the .zip file of io_export_catt for Blender for Mac v. 2.79b, the status bar says it has installed the Add-on from the file, but no CATT Add-on appears in the list to enable. 

Thanks for your help!

**Comment by berriganator** [comment]
Hello: installation to Blender 2.79b also fails.

**Comment by PyrApple** [comment]
Could you try again the install on Blender 2.93 with the latest version (branch master)

**Comment by berriganator** [comment]
Hello: Great, I tried installation of the branch master on Blender 2.93 and the installation is successful in the preferences pane. However, even when enabled as an Add-on, CATT is not available as an export option in the menu File > Export. Am I missing where the CATT export function should be?

**Comment by PyrApple** [comment]
The add-on is in 3D View > Sidebar

**Comment by berriganator** [comment]
It is nowhere to be found.

**Comment by berriganator** [comment]
Found it! Will test. :)
