### ISSUE TITLE
Blender 2.79b installation fails

### ISSUE THREAD

**Issue by berriganator** [PyrApple/io_export_catt#3]
Hello: After installing the .zip file of io_export_catt for Blender for Mac v. 2.79b, the status bar says it has installed the Add-on from the file, but no CATT Add-on appears in the list to enable.

**Comment by PyrApple** [comment]
Import failed due "." in add-on folder name (added upon zip creation by GitHub for v1.0 tag archive). Added "io_export_catt.zip" to that release, with valid folder name. Download it instead of the Source Code zip.
